services:
  flask_learning:
    build:
      context: .
      dockerfile: docker/Dockerfile.flask_learning
    image: flask_learning:v1
    container_name: flask_learning
    ports:
      - "5000:5000"
    environment:
      - DEBUG=${DEBUG:-false}
    # volumes:
    #   - ./flask_learning:/app
    restart: unless-stopped
    networks:
      - app-network

  fastapi_learning:
    build:
      context: .
      dockerfile: docker/Dockerfile.fastapi_learning
    image: fastapi_learning:v1
    container_name: fastapi_learning
    ports:
      - "8000:8000"
    environment:
      - DEBUG=${DEBUG:-false}
    # volumes:
    #   - ./fastapi_learning:/app
    restart: unless-stopped
    networks:
      - app-network

  django_learning:
    build:
      context: .
      dockerfile: docker/Dockerfile.django_learning
    image: django_learning:v1
    container_name: django_learning
    ports:
      - "8001:8001"
    environment:
      - DEBUG=${DEBUG:-false}
    # volumes:
    #   - ./django_learning:/app
    restart: unless-stopped
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
