name: Paladin
channels:
  - conda-forge
  - defaults
dependencies:
  - python
  # data analysis
  - numpy
  - scipy
  - pandas
  - matplotlib
  # file
  - pyyaml
  # devtools
  - ruff
  - black
  - isort
  # test
  - pytest
  - tox
  - coverage
  # build
  - build
  - pip
  - setuptools
  - hatch
  - wheel
  # extension
  - cython
  - pybind11
  # utils
  - tqdm
  - pip:
      - pip_search
