[package]
name = "pyo3_example"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pyo3 = "*"

[lib]
name = "pyo3_example"
crate-type = ["cdylib"]
